version: '2.1'
volumes:
   prometheus_data: {}
   grafana_data: {}

services:
  angular-app:
    build: Front-end/
    image: angular
    restart: always
    container_name: Angular
    network_mode: "host"
    hostname: localhost
    ports:
      - 4200:4200
    healthcheck:
      test: "exit 0"   
